# Generated by Django 5.1.2 on 2024-12-23 06:57

import classes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('labs', '0003_alter_lab_lab_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classcomment',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classlocation',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classlocation',
            name='lab_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labs.lab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachclass',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachclass',
            name='teacher_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_id'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('estimated_time', models.FloatField()),
                ('safety_tags', models.JSONField(default=list)),
                ('experiment_method_tags', models.CharField(max_length=50)),
                ('submission_type_tags', models.CharField(max_length=50)),
                ('other_tags', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=classes.models.RandomFileName('experiment_files/'))),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='classes.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=classes.models.RandomFileName('experiment_images/'))),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classes.experiment')),
            ],
        ),
    ]
