# Generated by Django 5.1.2 on 2024-12-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('safety_equipments', models.JSONField(blank=True, default=list, null=True)),
                ('safety_notes', models.TextField(blank=True, null=True)),
                ('lab_image', models.ImageField(blank=True, null=True, upload_to='lab_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ManageLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(db_column='lab_id', on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
            ],
            options={
                'db_table': 'manage_lab',
            },
        ),
    ]
