# Generated by Django 5.1.2 on 2024-12-18 16:19

import labs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_image',
            field=models.ImageField(blank=True, null=True, upload_to=labs.models.RandomFileName('lab_images/')),
        ),
    ]
