# Generated by Django 5.1.2 on 2024-12-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_managelab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='safety_equipments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='safety_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
