# Generated by Django 5.1.2 on 2024-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_lab_safety_equipments_lab_safety_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_images/'),
        ),
    ]
