# Generated by Django 5.1.2 on 2024-12-23 08:04

import labs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_lab_lab_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to=labs.models.RandomFileName('lab_map/')),
        ),
    ]
