services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/nginx/html:/usr/share/nginx/html
      - static_volume:/static
      - media_volume:/media
    networks:
      - web_network

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    volumes:
      - ./server:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - ""
    depends_on:
      - db
    networks:
      - web_network
      - db_network

  
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    expose:
      - ""
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/postgresql/data



volumes:
  db_data:
  static_volume:
  media_volume:


networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge