FROM python:3.10

WORKDIR /code

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

#RUN python manage.py collectstatic --noinput && \
#    python manage.py makemigrations && \
#    python manage.py migrate

# RUN python manage.py collectstatic


RUN pip install gunicorn


CMD ["sh", "-c", "python manage.py collectstatic --noinput && gunicorn --workers=4 --bind 0.0.0.0:<port> tlsa_server.wsgi:application"]