# Generated by Django 5.1.2 on 2024-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlsa_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsa_user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('manager', 'Manager')], max_length=20),
        ),
    ]
