# Generated by Django 5.1.2 on 2024-12-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlsa_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsa_user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlsa_user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlsa_user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlsa_user',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
