# Generated by Django 5.1.2 on 2024-12-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlsa_server', '0002_alter_tlsa_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlsa_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
