# Generated by Django 5.1.2 on 2024-12-18 06:24

import tlsa_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlsa_server', '0002_alter_tlsa_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsa_user',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tlsa_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tlsa_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=tlsa_server.models.RandomFileName('profile_pics/')),
        ),
        migrations.AlterField(
            model_name='tlsa_user',
            name='real_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tlsa_user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('manager', 'Manager'), ('teachingAffairs', 'TeachingAffairs')], max_length=20),
        ),
    ]
