# Generated by Django 5.1.2 on 2024-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlsa_server', '0003_tlsa_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlsa_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
