# Generated by Django 5.1.2 on 2024-12-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices_sent', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='noticecompletion',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='notices.notice'),
        ),
        migrations.AddField(
            model_name='noticecompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_completions', to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='noticecontenttag',
            name='notice_content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.noticecontent'),
        ),
        migrations.AddField(
            model_name='noticerow',
            name='notice_content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.noticecontent'),
        ),
        migrations.AddField(
            model_name='noticerow',
            name='notice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.notice'),
        ),
        migrations.AddField(
            model_name='noticecontenttag',
            name='notice_tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.noticetag'),
        ),
        migrations.AlterUniqueTogether(
            name='noticerow',
            unique_together={('notice_id', 'notice_content_id')},
        ),
        migrations.AlterUniqueTogether(
            name='noticecontenttag',
            unique_together={('notice_content_id', 'notice_tag_id')},
        ),
    ]
