# Generated by Django 5.1.2 on 2024-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticecontent',
            name='content',
        ),
        migrations.AddField(
            model_name='noticecontent',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='notice_files/'),
        ),
        migrations.AddField(
            model_name='noticecontent',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='noticecontent',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticecontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], max_length=10),
        ),
    ]
