# Generated by Django 5.1.2 on 2024-12-20 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_remove_noticecontent_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticerow',
            name='notice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='notices.notice'),
        ),
    ]
